apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-new-cluster
spec:
  kafka:
    version: 2.8.0
    jvmOptions:
      -Xms: 128m
      -Xmx: 256m
    resources:
      requests:
        memory: 256Mi
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
      - name: external
        port: 9094
        type: nodeport
        tls: false
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Mi
        deleteClaim: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
  zookeeper:
    replicas: 1
    resources:
      requests:
        memory: 128Mi
    jvmOptions:
      -Xmx: 128m
    storage:
      type: persistent-claim
      size: 100Mi
      deleteClaim: false
