apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: mirror-maker
spec:
  version: 2.8.0
  replicas: 1
  connectCluster: "target-cluster"
  clusters:
  - alias: "source-cluster"
    bootstrapServers: my-old-cluster-kafka-bootstrap.stage-old:9092
  - alias: "target-cluster"
    bootstrapServers: my-new-cluster-kafka-bootstrap:9092
    config: # kafka connect configuration for mirror maker
      config.providers: file
      config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
      config.storage.replication.factor: -1
      config.storage.topic: kafka-mirror-maker-configs
      connector.client.config.override.policy: All
      group.id: kafka-mirror-maker
      offset.storage.replication.factor: -1
      offset.storage.topic: kafka-mirror-maker-offsets
      producer.acks: all
      status.storage.replication.factor: -1
      status.storage.topic: kafka-mirror-maker-status
  mirrors:
  - sourceCluster: "source-cluster"
    targetCluster: "target-cluster"
    sourceConnector:
      tasksMax: 10
      config:
        replication.factor: 1 # for mirrored topics
        offset-syncs.topic.replication.factor: 1
        sync.topic.acls.enabled: "false"
        refresh.topics.interval.seconds: 60 # check for new topics: default 600
        replication.policy.separator: "" # in case of renaming
        replication.policy.class: "io.strimzi.kafka.connect.mirror.IdentityReplicationPolicy" # topic keeps the original name
    heartbeatConnector:
      config:
        heartbeats.topic.replication.factor: 1
    checkpointConnector:
      config:
        checkpoints.topic.replication.factor: 1
        refresh.groups.interval.seconds: 600 # check for consumer groups: default 600
        sync.group.offsets.enabled: true # sync consumer group offsets
        sync.group.offsets.interval.seconds: 60 # frequency of synchronization
        emit.checkpoints.interval.seconds: 60 # frequency of the checks for synchronization
        replication.policy.class: "io.strimzi.kafka.connect.mirror.IdentityReplicationPolicy"
    topicsPattern: ".*" # regexp or comma separated list
    groupsPattern: ".*" # regexp or comma separated list
  jvmOptions:
    -Xms: 128m
    -Xmx: 256m
  resources:
    requests:
      memory: 256Mi
  logging:
    loggers:
      log4j.appender.stdout: org.apache.log4j.ConsoleAppender
      log4j.appender.stdout.layout: org.apache.log4j.PatternLayout
      log4j.appender.stdout.layout.ConversionPattern: '[%d] %p %m (%c)%n'
      log4j.logger.org.I0Itec.zkclient: ERROR
      log4j.logger.org.apache.zookeeper: ERROR
      log4j.logger.org.reflections: ERROR
      log4j.rootLogger: INFO, stdout
    type: inline
