apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
spec:
  type: ClusterIP
  ports:
  - name: kong-proxy-https
    port: 443
    targetPort: 8443
    protocol: TCP
  - name: kong-proxy-http
    port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: ingress-kong